/**
 * Application-wide constants
 * Centralized configuration values to avoid magic numbers
 */

export const AUTH_CONSTANTS = {
  // Login & Security
  MAX_LOGIN_ATTEMPTS: 5,
  ACCOUNT_LOCK_DURATION_MINUTES: 30,
  
  // JWT & Tokens
  JWT_EXPIRY: '24h',
  MFA_TEMP_TOKEN_EXPIRY: '5m',
  
  // Email Verification
  EMAIL_VERIFICATION_CODE_EXPIRY_MINUTES: 30,
  EMAIL_VERIFICATION_CODE_LENGTH: 6,
  EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS: 24,
  
  // Password Reset
  PASSWORD_RESET_CODE_EXPIRY_MINUTES: 30,
  PASSWORD_RESET_CODE_LENGTH: 6,
  PASSWORD_RESET_TOKEN_EXPIRY_HOURS: 1,
  
  // Phone Verification
  PHONE_VERIFICATION_CODE_EXPIRY_MINUTES: 10,
  PHONE_VERIFICATION_CODE_LENGTH: 6,
  PHONE_PASSWORD_RESET_CODE_EXPIRY_MINUTES: 10,
  
  // MFA
  MFA_BACKUP_CODES_COUNT: 10,
  MFA_BACKUP_CODE_LENGTH: 6,
} as const;

export const COMMISSION_CONSTANTS = {
  DEFAULT_AGENT_COMMISSION_RATE: 6.0,
  DEFAULT_CLOSER_COMMISSION_RATE: 10.0,
} as const;

export const BILLING_CONSTANTS = {
  DEFAULT_INVOICE_DUE_DAYS: 30,
  DEFAULT_TAX_RATE: 0,
  BCRYPT_SALT_ROUNDS: 12,
} as const;

export const PAGINATION_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
} as const;

export const VALIDATION_CONSTANTS = {
  // Password
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  
  // General
  MAX_STRING_LENGTH: 255,
  MAX_TEXT_LENGTH: 5000,
  MAX_DESCRIPTION_LENGTH: 1000,
  
  // File Upload
  MAX_FILE_SIZE_MB: 10,
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
  
  // Phone
  MIN_PHONE_LENGTH: 10,
  MAX_PHONE_LENGTH: 20,
} as const;

export const NUMBER_GENERATION = {
  // Number padding
  INVOICE_NUMBER_PADDING: 4,
  CONTRACT_NUMBER_PADDING: 4,
  TICKET_NUMBER_PADDING: 4,
  PROJECT_NUMBER_PADDING: 4,
  
  // Prefixes
  INVOICE_PREFIX: 'INV',
  CONTRACT_PREFIX: 'MC',
  TICKET_PREFIX: 'TKT',
  PROJECT_PREFIX: 'PRJ',
} as const;

export const TIME_CONSTANTS = {
  // Durations in milliseconds
  ONE_MINUTE_MS: 60 * 1000,
  FIVE_MINUTES_MS: 5 * 60 * 1000,
  TEN_MINUTES_MS: 10 * 60 * 1000,
  THIRTY_MINUTES_MS: 30 * 60 * 1000,
  ONE_HOUR_MS: 60 * 60 * 1000,
  ONE_DAY_MS: 24 * 60 * 60 * 1000,
  
  // Cache durations
  CACHE_5_MINUTES: 5 * 60,
  CACHE_10_MINUTES: 10 * 60,
  CACHE_30_MINUTES: 30 * 60,
  CACHE_1_HOUR: 60 * 60,
} as const;

